### ISSUE TITLE
Github Workflows

### ISSUE THREAD

**Issue by averyfreeman** [kaisenlinux/kaisen-timeshift-apt#1]
Hi, 

I like the look of your project, I'm definitely going to check it out

I just wanted to mention that while going through various forks of timeshift, I noticed Linux Mint is using github workflows for CI/CD, and I thought you may want to have a look in case it might help your project, as well:  https://github.com/linuxmint/timeshift

Have a nice day,
Avery

**Comment by kaisenlinux** [comment]
Hello,

GitHub is a mirror of: https://gitlab.com/kaisenlinux

We have not a time for the moment to set the workflows for the CI/CD from GitLab for our packages.
It's in our todo list.

Thank you for the attention.
Best regards,
Kaisen Linux team.

**Comment by averyfreeman** [comment]
Oh my apologies for not seeing mirror notice.

`Kaisen` is very nice - it is basically how I would customize Debian if I were installing myself (minus the re-branding) but you did it for us.  So very nice of you! A true public service.

I have questions, but I'll direct them to the forum since that seems more appropriate. Thanks again!
`Avery`
